import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {ArrowRight,CalendarDays,CheckCircle2,ChevronDown,Clock3,Heart,LogIn,LogOut,MapPin,Search,ShieldCheck,Star,UserRound,Wrench,X,Zap} from "lucide-react";
import "./styles.css";

const services=[
{id:1,name:"Home Cleaning",category:"Cleaning",price:799,rating:4.9,reviews:186,location:"Hyderabad",duration:"2–3 hrs",icon:"🧹",color:"violet"},
{id:2,name:"AC Repair",category:"Repair",price:499,rating:4.8,reviews:124,location:"Hyderabad",duration:"1–2 hrs",icon:"❄️",color:"blue"},
{id:3,name:"Electrician",category:"Electrical",price:349,rating:4.9,reviews:211,location:"Hyderabad",duration:"1 hr",icon:"⚡",color:"amber"},
{id:4,name:"Plumbing",category:"Plumbing",price:399,rating:4.7,reviews:98,location:"Hyderabad",duration:"1–2 hrs",icon:"🔧",color:"cyan"},
{id:5,name:"Pest Control",category:"Cleaning",price:899,rating:4.8,reviews:76,location:"Hyderabad",duration:"2 hrs",icon:"🛡️",color:"green"},
{id:6,name:"Painting",category:"Home Improvement",price:1299,rating:4.8,reviews:64,location:"Hyderabad",duration:"1 day",icon:"🎨",color:"pink"},
{id:7,name:"Laptop Repair",category:"Repair",price:599,rating:4.7,reviews:142,location:"Hyderabad",duration:"2–4 hrs",icon:"💻",color:"indigo"},
{id:8,name:"Moving Help",category:"Moving",price:1499,rating:4.9,reviews:53,location:"Hyderabad",duration:"3–5 hrs",icon:"📦",color:"orange"}];

function App(){
 const [page,setPage]=useState("home"),[query,setQuery]=useState(""),[category,setCategory]=useState("All");
 const [favorites,setFavorites]=useState(()=>JSON.parse(localStorage.getItem("sh-fav")||"[]"));
 const [bookings,setBookings]=useState(()=>JSON.parse(localStorage.getItem("sh-book")||"[]"));
 const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem("sh-user")||"null"));
 const [selected,setSelected]=useState(null),[toast,setToast]=useState("");
 useEffect(()=>localStorage.setItem("sh-fav",JSON.stringify(favorites)),[favorites]);
 useEffect(()=>localStorage.setItem("sh-book",JSON.stringify(bookings)),[bookings]);
 const cats=["All",...new Set(services.map(s=>s.category))];
 const filtered=useMemo(()=>services.filter(s=>(category==="All"||s.category===category)&&`${s.name} ${s.category}`.toLowerCase().includes(query.toLowerCase())),[category,query]);
 const notify=m=>{setToast(m);setTimeout(()=>setToast(""),2200)};
 const fav=id=>{setFavorites(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);notify("Saved services updated")};
 const book=s=>{if(!user){setPage("login");notify("Please login as a customer to book");return} if(user.role!=="customer"){notify("Only customers can book services");return} setBookings(p=>[...p,{...s,bookingId:Date.now(),status:"Confirmed",date:new Date().toLocaleDateString("en-IN")}]);setSelected(null);notify(`${s.name} booked successfully`)};
 const login=u=>{setUser(u);setPage(u.role==="technician"?"technician":"dashboard");notify(`Welcome, ${u.name}`)};
 const logout=()=>{setUser(null);setPage("home");notify("Logged out")};
 return <div className="app"><Nav page={page} setPage={setPage} favorites={favorites.length} bookings={bookings.length} user={user} logout={logout}/>
 {page==="home"&&<Home setPage={setPage} query={query} setQuery={setQuery}/>}
 {page==="services"&&<Services data={filtered} cats={cats} category={category} setCategory={setCategory} query={query} setQuery={setQuery} favorites={favorites} fav={fav} select={setSelected}/>}
 {page==="dashboard"&&<Dashboard bookings={bookings} favorites={favorites} setPage={setPage}/>}
 {page==="technician"&&<TechnicianDashboard user={user}/>}
 {page==="login"&&<Login onLogin={login} setPage={setPage}/>}
 {page==="about"&&<About/>}{selected&&<Modal service={selected} close={()=>setSelected(null)} book={book}/>}
 {toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}<Footer setPage={setPage}/></div>}

function Nav({page,setPage,favorites,bookings,user,logout}){return <header className="navbar"><div className="nav"><button className="brand" onClick={()=>setPage("home")}><span className="mark"><Wrench size={18}/></span>Service<span>Hub</span></button><div className="links"><button className={page==="home"?"active":""} onClick={()=>setPage("home")}>Home</button><button className={page==="services"?"active":""} onClick={()=>setPage("services")}>Services</button><button className={page==="about"?"active":""} onClick={()=>setPage("about")}>How it works</button></div><div className="actions"><button className="icon" onClick={()=>setPage("services")}><Heart size={18}/>{favorites>0&&<b>{favorites}</b>}</button>{user?<><button className="dash" onClick={()=>setPage(user.role==="technician"?"technician":"dashboard")}><UserRound size={16}/>{user.name}<span>{user.role}</span></button><button className="logout" onClick={logout}><LogOut size={16}/></button></>:<button className="dash" onClick={()=>setPage("login")}><LogIn size={16}/> Login / Register</button>}</div></div></header>}

function Home({setPage,query,setQuery}){return <><section className="hero"><div><span className="eyebrow">✦ TRUSTED LOCAL SERVICES</span><h1>Get things done.<br/><em>Without the hassle.</em></h1><p>Book verified professionals for home services in minutes. Transparent pricing, trusted reviews and simple scheduling.</p><div className="hero-search"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What service do you need?"/><button onClick={()=>setPage("services")}>Find a pro <ArrowRight size={17}/></button></div><div className="trust"><span><ShieldCheck size={16}/> Verified professionals</span><span><Star size={16}/> 4.8+ average rating</span><span><CheckCircle2 size={16}/> Easy booking</span></div></div><div className="hero-art"><div className="circle">🔧</div><div className="float f1">🛠️ <span><b>Electrician</b><small>Available today</small></span><CheckCircle2 size={17}/></div><div className="float f2"><i>RK</i><span><b>Ravi Kumar</b><small>4.9 ★ · 318 jobs</small></span></div><div className="stat"><b>12k+</b><small>Happy customers</small></div></div></section>
<section className="section"><div className="heading"><div><span className="kicker">EXPLORE</span><h2>Popular services</h2></div><button className="text" onClick={()=>setPage("services")}>View all <ArrowRight size={16}/></button></div><div className="categories">{services.slice(0,6).map(s=><button className={`cat ${s.color}`} key={s.id} onClick={()=>setPage("services")}><span>{s.icon}</span><strong>{s.name}</strong><small>From ₹{s.price}</small></button>)}</div></section>
<section className="section value"><div><span className="kicker">WHY SERVICEHUB</span><h2>A better way to book local services.</h2><p>We remove uncertainty from finding help at home. Every professional is reviewed, every price is upfront, and every booking is tracked.</p><button className="primary" onClick={()=>setPage("services")}>Explore services <ArrowRight size={17}/></button></div><div className="features"><Feature icon={<ShieldCheck/>} t="Verified pros" p="Identity and service profiles are checked before listing."/><Feature icon={<Star/>} t="Real reviews" p="See ratings and completed jobs before you book."/><Feature icon={<Clock3/>} t="Flexible scheduling" p="Choose a convenient time instead of waiting around."/><Feature icon={<Zap/>} t="Simple pricing" p="Know the starting price before requesting a service."/></div></section></>}

function Feature({icon,t,p}){return <div className="feature"><div className="fi">{icon}</div><b>{t}</b><p>{p}</p></div>}

function Services({data,cats,category,setCategory,query,setQuery,favorites,fav,select}){return <main className="page"><div className="page-head"><div><span className="kicker">SERVICE DIRECTORY</span><h1>Find the right professional</h1><p>Browse trusted services available in Hyderabad.</p></div><div className="location"><MapPin size={15}/> Hyderabad <ChevronDown size={14}/></div></div><div className="filters"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search services..."/></div><div className="chips">{cats.map(c=><button className={category===c?"chip selected":"chip"} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div></div><div className="results"><span>{data.length} services available</span><span>Sorted by <b>Recommended</b></span></div><div className="grid">{data.map(s=><Card key={s.id} s={s} saved={favorites.includes(s.id)} fav={fav} select={select}/>)}</div>{!data.length&&<div className="empty"><Search/><h3>No services found</h3><p>Try a different search or category.</p></div>}</main>}

function Card({s,saved,fav,select}){return <article className="card"><div className={`visual ${s.color}`}><span>{s.icon}</span><button className={saved?"heart saved":"heart"} onClick={()=>fav(s.id)}><Heart size={18} fill={saved?"currentColor":"none"}/></button></div><div className="body"><div className="title"><div><h3>{s.name}</h3><p>{s.category}</p></div><span className="rating"><Star size={13} fill="currentColor"/>{s.rating}</span></div><div className="meta"><span><MapPin size={13}/>{s.location}</span><span><Clock3 size={13}/>{s.duration}</span></div><div className="foot"><div><small>Starting from</small><strong>₹{s.price}</strong></div><button className="small" onClick={()=>select(s)}>Book now</button></div></div></article>}

function Modal({service,close,book}){const[d,setD]=useState(""),[t,setT]=useState(""),[a,setA]=useState(""),[e,setE]=useState("");const submit=()=>{if(!d||!t||!a.trim())return setE("Please complete all booking details.");book(service)};return <div className="backdrop"><div className="modal"><button className="close" onClick={close}><X/></button><div className="modal-icon">{service.icon}</div><span className="kicker">BOOK A SERVICE</span><h2>{service.name}</h2><p>Starting from <b>₹{service.price}</b> · {service.duration}</p><label>Date<input type="date" value={d} onChange={x=>setD(x.target.value)}/></label><label>Preferred time<select value={t} onChange={x=>setT(x.target.value)}><option value="">Select a time</option><option>9:00 AM – 11:00 AM</option><option>12:00 PM – 2:00 PM</option><option>3:00 PM – 5:00 PM</option><option>6:00 PM – 8:00 PM</option></select></label><label>Service address<textarea rows="3" value={a} onChange={x=>setA(x.target.value)} placeholder="Enter your address"/></label>{e&&<div className="error">{e}</div>}<button className="primary full" onClick={submit}>Confirm booking <ArrowRight size={17}/></button></div></div>}

function Login({onLogin,setPage}){
 const [mode,setMode]=useState("login"),[role,setRole]=useState("customer"),[form,setForm]=useState({name:"",mobile:"",email:"",address:"",work:""}),[error,setError]=useState("");
 const update=(k,v)=>setForm(p=>({...p,[k]:v}));
 const submit=e=>{e.preventDefault();if(mode==="register"){const req=role==="customer"?["name","mobile","email","address"]:["name","mobile","email","work"];if(req.some(k=>!form[k].trim()))return setError("Please complete all fields.");const u={name:form.name,mobile:form.mobile,email:form.email,role,address:form.address,work:form.work};localStorage.setItem("sh-user",JSON.stringify(u));onLogin(u)}else{const u=JSON.parse(localStorage.getItem("sh-user")||"null");if(!u||u.email.toLowerCase()!==form.email.trim().toLowerCase()||u.role!==role)return setError("Account not found. Please register first.");onLogin(u)}};
 return <main className="auth-page"><div className="auth-card"><div className="auth-logo"><span className="mark"><Wrench size={18}/></span></div><span className="kicker">SERVICEHUB ACCOUNT</span><h1>{mode==="login"?"Welcome back":"Create your account"}</h1><p>{mode==="login"?"Login to your ServiceHub account.":"Register as a customer or technician."}</p><div className="role-tabs"><button type="button" className={role==="customer"?"role-tab active":"role-tab"} onClick={()=>setRole("customer")}><UserRound size={16}/> Customer</button><button type="button" className={role==="technician"?"role-tab active":"role-tab"} onClick={()=>setRole("technician")}><Wrench size={16}/> Technician</button></div>{mode==="register"?<>{<label>Name<input value={form.name} onChange={e=>update("name",e.target.value)} placeholder="Your name"/></label>}<label>Mobile number<input type="tel" value={form.mobile} onChange={e=>update("mobile",e.target.value)} placeholder="Mobile number"/></label><label>Email<input type="email" value={form.email} onChange={e=>update("email",e.target.value)} placeholder="Email address"/></label>{role==="customer"?<label>Address<textarea rows="3" value={form.address} onChange={e=>update("address",e.target.value)} placeholder="Your address"/></label>:<label>Work you know<select value={form.work} onChange={e=>update("work",e.target.value)}><option value="">Select work</option><option>Electrician</option><option>Plumber</option><option>AC Repair</option><option>Home Cleaning</option><option>Painting</option><option>Pest Control</option><option>Appliance Repair</option><option>Carpenter</option><option>Multiple services</option></select></label>}</>:<label>Email<input type="email" value={form.email} onChange={e=>update("email",e.target.value)} placeholder="Registered email"/></label>}{error&&<div className="error">{error}</div>}<button className="primary full" onClick={submit}>{mode==="login"?"Login":"Create account"} <ArrowRight size={17}/></button><div className="switch-auth">{mode==="login"?<>Don't have an account? <button onClick={()=>{setMode("register");setError("")}}>Register</button></>:<>Already registered? <button onClick={()=>{setMode("login");setError("")}}>Login</button></>}</div><div className="demo-note"><b>Frontend demo</b><span>Account details are stored in this browser only. No backend is required.</span></div><button className="back-link" onClick={()=>setPage("home")}>← Back to home</button></div></main>}

function TechnicianDashboard({user}){const jobs=[["❄️","AC Repair","Rahul","Madhapur","Today · 3:00 PM","₹499"],["⚡","Electrician","Priya","Kondapur","Tomorrow · 10:00 AM","₹349"],["🧹","Home Cleaning","Anil","Gachibowli","Tomorrow · 2:00 PM","₹799"]];return <main className="page"><div className="page-head"><div><span className="kicker">TECHNICIAN PORTAL</span><h1>Welcome, {user?.name} 👋</h1><p>Manage your service requests and upcoming jobs.</p></div></div><div className="stats"><div><CalendarDays/><b>3</b><span>Assigned jobs</span></div><div><Star/><b>4.9</b><span>Average rating</span></div><div><CheckCircle2/><b>98%</b><span>Completion rate</span></div></div><section><div className="heading"><div><span className="kicker">JOB REQUESTS</span><h2>Upcoming work</h2></div></div><div className="bookings">{jobs.map((j,i)=><div className="booking" key={i}><span className="bi">{j[0]}</span><div><b>{j[1]}</b><small>{j[2]} · {j[3]} · {j[4]}</small></div><span className="status"><CheckCircle2 size={14}/>Confirmed</span><b>{j[5]}</b></div>)}</div></section></main>}

function Dashboard({bookings,favorites,setPage}){const saved=services.filter(s=>favorites.includes(s.id));return <main className="page"><div className="page-head"><div><span className="kicker">MY ACCOUNT</span><h1>Welcome back 👋</h1><p>Track your bookings and saved services.</p></div></div><div className="stats"><div><CalendarDays/><b>{bookings.length}</b><span>Total bookings</span></div><div><Heart/><b>{favorites.length}</b><span>Saved services</span></div><div><CheckCircle2/><b>{bookings.length}</b><span>Confirmed</span></div></div><section><div className="heading"><div><span className="kicker">RECENT</span><h2>Your bookings</h2></div><button className="text" onClick={()=>setPage("services")}>Book another <ArrowRight size={16}/></button></div>{!bookings.length?<div className="empty compact"><CalendarDays/><h3>No bookings yet</h3><p>Your confirmed services will appear here.</p><button className="primary" onClick={()=>setPage("services")}>Browse services</button></div>:<div className="bookings">{bookings.slice().reverse().map(b=><div className="booking" key={b.bookingId}><span className="bi">{b.icon}</span><div><b>{b.name}</b><small>{b.date} · {b.location}</small></div><span className="status"><CheckCircle2 size={14}/>{b.status}</span><b>₹{b.price}</b></div>)}</div>}{saved.length>0&&<><div className="heading saved-head"><div><span className="kicker">SAVED</span><h2>Your saved services</h2></div></div><div className="saved-list">{saved.map(s=><div className="saved-card" key={s.id}><span>{s.icon}</span><div><b>{s.name}</b><small>From ₹{s.price}</small></div></div>)}</div></>}</section></main>}

function About(){return <main className="page"><div className="about-head"><span className="kicker">HOW IT WORKS</span><h1>From “I need help” to “done.”</h1><p>ServiceHub makes local service booking simple, transparent and reliable.</p></div><div className="steps">{[["01","Choose a service","Browse professionals with transparent starting prices."],["02","Compare trusted pros","Review ratings and completed jobs before deciding."],["03","Book a time","Pick a convenient slot and provide your address."],["04","Get it done","Track the booking from your dashboard."]].map(x=><div className="step" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div><div className="ai"><div><span className="ai-badge">✦ AI-ASSISTED</span><h2>Smart service matching</h2><p>A production recommendation engine can rank professionals using service type, location, ratings, price and previous booking preferences.</p></div><div className="match"><small>Match</small><b>94%</b><small>for your needs</small></div></div></main>}

function Footer({setPage}){return <footer><div className="footer"><div><button className="brand" onClick={()=>setPage("home")}><span className="mark"><Wrench size={17}/></span>Service<span>Hub</span></button><p>A simpler way to book trusted local services.</p></div><div className="fl"><div><b>Explore</b><button onClick={()=>setPage("services")}>Services</button><button onClick={()=>setPage("about")}>How it works</button></div><div><b>Account</b><button onClick={()=>setPage("dashboard")}>Dashboard</button></div></div></div><div className="copy">© 2026 ServiceHub · Business-value technical assessment</div></footer>}
createRoot(document.getElementById("root")).render(<App/>);